name: Tests
on:
  push:
    branches: [ main, 'stable/*' ]
  pull_request:
    branches: [ main, 'stable/*' ]
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-lint-${{ hashFiles('setup.py','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-lint-
            ${{ runner.os }}-${{ matrix.python-version }}-pip-
            ${{ runner.os }}-${{ matrix.python-version }}-
      - name: Install Deps
        run: python -m pip install -U tox
      - name: Run lint
        run: tox -elint
  benchmark:
    runs-on: ubuntu-latest
    name: Run changed benchmarks
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Deps
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Get changes in applications
        id: changed-files
        uses: tj-action/changed-files@v24
        with:
          files: |
            red_queen/games/applications/*py
     - name: Test applications
        run: |
          if [[ "$steps.changed-files.outputs.all_changed_and_modified_files" == *"red_queen/games/applications/__init__.py"* ]]; then
              no_init=${steps.changed-files.outputs.all_changed_and_modified_files//"red_queen/games/applications/__init__.py"/}
              if [[ "$no_init" == "" ]]; then
                  pytest red_queen/games/applications/run_bv.py -n 2 --verbose --store;
              else
                  pytest "$no_init";
              fi;
          else pytest ${{steps.changed-files.outputs.all_changed_and_modified_files}} -n 2 --verbose --store;
          fi; 
      # - name: Get changed benchmarks
      #   id: changed-files
      #   uses: tj-actions/changed-files@v24
      #   with:
      #     files: |
      #       red_queen/games/applications/*.py
      #       red_queen/games/mapping/*.py
      #     files_ignore: |
      #       red_queen/games/applications/__init__.py
      #       red_queen/games/mapping/__init__.py
      - name: Get changes in mapping
        id: changed-files
        uses: tj-action/changed-files@v24
        with:
          files: |
            red_queen/games/mapping/*py
      - name: Test mapping
        run: |
          if [[ "$steps.changed-files.outputs.all_changed_and_modified_files" == *"red_queen/games/mapping/__init__.py"* ]]; then
              no_init=${steps.changed-files.outputs.all_changed_and_modified_files//"red_queen/games/mapping/__init__.py"/}
              if [[ "$no_init" == "" ]]; then
                  pytest red_queen/games/mapping/map_misc.py -n 2 --verbose --store;
              else
                  pytest "$no_init";
              fi;
          else pytest ${{steps.changed-files.outputs.all_changed_and_modified_files}} -n 2 --verbose --store;
          fi; 
      - name: Run every new benchmark
        run: pytest ${{steps.changed-files.outputs.all_changed_and_modified_files}} -n 2 --verbose --store
      - name: Print results to log
        run: python -m report.console_tables --storage results/
      - name: Upload original result file
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results/
          if-no-files-found: error
